name: Shield TV Card
description: 📺 TV Remote Card for Nvidia Shield
type: lovelace
keywords:
  - tvcard
  - remote
  - Nvidia
  - Shield
author:
  name: mar_robHD, Gangoke
license: Apache License, Version 2.0
files:
  - shieldtv-card.js
  - shieldtv-card-editor.js
